import type { Copy } from ".";
import type { ptUi } from "./pt";

const enUi: typeof ptUi = {
  locale: "en-US",
  org: "your-company",
  repo: "engineering-team",
  shortcuts: "Shortcuts",
  cv: "Résumé PDF (in Portuguese)",
  title: (role) => `Hire Thiago Sampaio as ${role}`,
  open: "Open",
  mergeInto: (n) => `wants to merge ${n} commits into`,
  fromBranch: "from",
  tablist: "Pull request sections",
  tabs: { conversation: "Conversation", commits: "Commits", checks: "Checks", files: "Files changed" },
  diffstat: (n) => `${n} lines added, 0 removed`,
  footer: "Written as a pull request. No GitHub was harmed.",

  prefs: "Preferences",
  palette: "Color theme",
  palettes: { lime: "Lime", ocean: "Ocean", rose: "Rose", amber: "Amber", light: "Light" },
  language: "Language",

  described: "opened this pull request",
  author: "Author",
  hSummary: "Summary",
  hNow: "What this merge brings",
  hTest: "How to test",
  hChecklist: "Checklist",
  addedLabels: "added the labels",
  addedCommits: (n) => `added ${n} commits`,
  seeCommits: (n) => `see all ${n} commits →`,
  selfReviewed: "reviewed their own changes",
  selfReview: "Self-review",
  principlesIntro: "Principles that guide my work, annotated in PRINCIPLES.md:",

  allPassed: "All checks have passed",
  checksLine: (n) => `${n} checks on stack, principles and GitHub`,
  ghDown: "GitHub is not responding right now",
  ghLoading: "querying GitHub…",
  ghLine: (repos, stars, last) => `${repos} repositories, ${stars} stars, last push ${last}`,
  details: "details",
  noConflicts: "No conflicts with the base branch",
  noConflictsText: "Based in Fortaleza, Brazil. This branch can land in your codebase without rework.",
  merge: "Merge pull request",
  confirmQ: "Confirm merge?",
  confirmNext: "The next step is a conversation.",
  confirm: "Confirm merge",
  mailSubject: "About PR #5232",
  copyEmail: "copy email",
  copied: "email copied ✓",
  cancel: "cancel",

  sidebar: "Pull request details",
  reviewers: "Reviewers",
  reviewPending: "You · review pending",
  assignee: "Assignee",
  labelsH: "Labels",
  milestone: "Milestone",
  milestoneText: "S4E · legacy ERP modernization",
  attachments: "Attachments",

  commitsOf: (y) => `Commits from ${y}`,
  openScope: (s) => `Open ${s}`,

  checksPassed: (n) => `${n} checks passed`,
  oneRunning: ", 1 in progress",
  oneNeutral: ", 1 neutral",
  verifications: (n) => `${n} checks · ok`,
  lintName: "lint / principles",
  lintRules: (n) => `${n} rules · 0 warnings`,
  ghName: "github / public activity",
  live: "live · api.github.com",
  passed: "passed",
  running: "in progress",
  neutral: "neutral",
  ghFailed: "GitHub did not respond. Try again later or open the profile.",
  loading: "querying…",
  repos: "public repositories",
  stars: "stars",
  lastPush: "last push",
  langs: "recent languages",

  files: "Files",
  binary: "binary file",
  screenshot: (t) => `Screenshot: ${t}`,
  diff: { status: "status", year: "year", role: "role", result: "result" },
};

export const en: Copy = {
  meta: {
    title: "Thiago Sampaio · Senior Software Engineer",
    description: "Thiago de Oliveira Sampaio, Senior Software Engineer in Fortaleza, Brazil. Full stack, applied AI and legacy system modernization.",
  },
  role: "Senior Software Engineer",
  bio: [
    "I build software that has to last: education platforms serving several institutions, legacy ERPs turned into modern architecture without stopping operations and, in my spare time, AI models that recognize hand-drawn Pokémon.",
    "Today I lead the modernization of a legacy ERP at S4E. Before that, I spent over three years at UniChristus, going from intern to full stack developer, designing Java and Go microservices and putting OCR, ICR and TTS to work grading exams. I hold a B.Sc. in Computer Science and I'm pursuing an M.Sc. in Applied Informatics at UNIFOR.",
  ],
  now: [
    {
      title: "Modernizing a legacy ERP",
      text: "At S4E since August 2026: I map the AS-IS, design the TO-BE and turn tacit knowledge into ADRs, API contracts and guides.",
    },
    {
      title: "Cities, river basins and urban waste",
      text: "I cluster cities with the City Clustering Algorithm and cross them with river basin discharge potential to predict how much plastic reaches rivers.",
    },
    {
      title: "LLMs without provider lock-in",
      text: "Professor Oak switches from local Ollama to any OpenAI-compatible API by changing 3 environment variables.",
    },
  ],
  status: { production: "in production", oss: "open source", research: "research", lab: "experiment" },
  linkLabel: { repo: "code", demo: "live demo", doc: "document" },
  projects: {
    exitus: {
      title: "Exitus Educational Ecosystem",
      role: "Full Stack · architecture",
      metric: { value: "12", label: "integrated modules" },
      summary:
        "Multi-tenant education platform serving several institutions from a single codebase: assessments, content editor, automated grading, messaging and more.",
      points: [
        "Java (Spring Boot) and Go microservices with independent deploys per domain.",
        "OCR, ICR and TTS pipelines that generate, read and grade exams with no manual steps.",
        "Modernized legacy modules, integrating internal and external systems through APIs.",
      ],
    },
    tiptap: {
      title: "Exitus Editor",
      role: "Author · library",
      summary:
        "Rich-text editor built on Tiptap/ProseMirror with formulas, images and content tooling, used as the single editor across several modules.",
      points: [
        "Minimal setup: one HTML element and one JS file.",
        "Built-in spell checker served by a Go microservice.",
        "Custom extensions for assessment content.",
      ],
    },
    profoak: {
      title: "Professor Oak",
      role: "Author",
      metric: { value: "3", label: "env vars to switch LLMs" },
      summary: "FastAPI assistant API with Professor Oak's permanent persona, independent of the LLM provider.",
      points: [
        "routes → services → models layers: the endpoint is tested with a fake LLM via dependency_overrides.",
        "Runs on local Ollama, vLLM or Groq/Together by changing only LLM_BASE_URL, LLM_API_KEY and LLM_MODEL.",
        "Strips <think> blocks from reasoning models so the persona stays intact and tokens don't blow up.",
        "Deployed with Docker Compose on Oracle Cloud Free Tier.",
      ],
    },
    pavimento: {
      title: "Asphalt pavement distress detection",
      role: "Researcher · undergraduate thesis",
      metric: { value: "93.2%", label: "precision" },
      summary: "Computer vision that detects and segments road defects from photos, with a hand-annotated custom dataset.",
      points: [
        "YOLOv11X with transfer learning from COCO weights.",
        "Segmentation with SAM2 and controlled fine-tuning against overfitting.",
        "Custom dataset with 757 annotated images.",
      ],
    },
    pokeguess: {
      title: "PokéGuess",
      role: "Author",
      metric: { value: "251", label: "Pokémon recognized" },
      summary: "You draw a Pokémon and the model tells you which one it is. Classifies Gen 1 and 2 sketches in real time.",
      points: ["Transfer learning with MobileNetV2 and two-phase fine-tuning.", "Heavy data augmentation to make up for few examples per class."],
    },
    ticket: {
      title: "Ticket Maker",
      role: "Author",
      summary: "RAG over the team's docs: indexes Markdown in pgvector and uses Gemini to draft tickets integrated with OpenProject.",
      points: ["Document ingestion with clean reindexing and configurable directories.", "Versioned Alembic migrations on PostgreSQL + pgvector."],
    },
    cca: {
      title: "City Clustering Algorithm",
      role: "Researcher · M.Sc.",
      metric: { value: "10⁶+", label: "sites processed" },
      summary: "CCA for regionalization: groups census tracts or population pixels into urban clusters by density and haversine distance.",
      points: [
        "KD-tree on the sphere: same result as the pairwise loop, running on millions of sites.",
        "Works with points (census tracts) and rasters (GPW).",
      ],
    },
    intent: {
      title: "Student message intent",
      role: "Researcher",
      summary: "NLP pipeline that classifies student messages by intent and decides which AI flow answers.",
      points: [
        "BERTimbau fine-tuning with HuggingFace.",
        "Gemini orchestration based on the detected category.",
        "Published at UNIFOR's 26th Graduate Studies and Research Meeting.",
      ],
    },
    medsystem: {
      title: "Med System",
      role: "Full Stack",
      summary: "Support for external physicians and UniChristus students: clinical care, diagnostic support, prescriptions and medical routines.",
      points: ["RabbitMQ messaging between Node.js services.", "React + Tailwind interface built for use during appointments."],
    },
    optasks: {
      title: "op-tasks-cli",
      role: "Author",
      summary: "npx CLI that syncs OpenProject tasks with local Markdown files, both ways.",
      points: ["Token stored in the home directory, never in the repo.", "Interactive project picker; downloads only open tasks assigned to you."],
    },
    bancosync: {
      title: "banco-sync-cli",
      role: "Author",
      summary: "Keeps SQL migration files in sync with the real PostgreSQL database, using Gemini to rewrite them and showing a diff before saving.",
      points: ["Structured JSON output from Gemini 2.5 Flash to preserve comments and style."],
    },
    katex: {
      title: "appKatex",
      role: "Author",
      summary: "Standalone, reactive (Signals) Angular directive that renders LaTeX with KaTeX in any component.",
      points: ["Detects $$…$$, \\[…\\] and \\(…\\) automatically.", "Escapes non-LaTeX HTML to prevent XSS."],
    },
    spell: {
      title: "Go spell checker",
      role: "Author",
      summary: "Containerized Go microservice that provides spell checking to Exitus Editor.",
      points: ["Isolated service with deploys independent from the editor."],
    },
    pokeia: {
      title: "PokeIA",
      role: "Author",
      summary: 'Semantic Pokédex: search "fire pokémon that flies" and get Charizard. Also recommends teams.',
      points: ["Vector search with Sentence-Transformers + FAISS."],
    },
    sqlguard: {
      title: "SQL Guard",
      role: "Author",
      summary: "Lab that shows secure and SQL-injection-vulnerable authentication flows side by side.",
      points: ["Supabase Functions on the backend, shadcn/ui + Radix on the frontend."],
    },
    agendamento: {
      title: "Appointment scheduling",
      role: "Author",
      summary: "Booking for psychologist appointments, with Google Sheets as the clinic dashboard, synced through Apps Script.",
      points: ["Angular front end, Express + MongoDB back end."],
    },
    readme: {
      title: "AI README generator",
      role: "Author",
      summary: "GPT-2 fine-tuned on GitHub READMEs to generate documentation, with an API and UI on HuggingFace Spaces.",
      points: ["Full pipeline: collection, preprocessing, training and evaluation."],
    },
    topatudo: {
      title: "TopaTudo",
      role: "Author",
      summary: "Marketplace for hiring service providers, with customer and provider journeys. My most-starred repo.",
      points: ["Test accounts: teste@teste.com or prestador@teste.com, password 12."],
    },
    termo: {
      title: "Termo Musical",
      role: "Author",
      summary: "A Wordle-style game where you guess the artist from 2 seconds of music. Daily challenge and practice mode.",
      points: ["Next.js 14 with App Router and the Web Audio API."],
    },
    blockchain: {
      title: "Clojure blockchain",
      role: "Author",
      summary: "A blockchain written entirely in Clojure, to understand immutability and hash chaining.",
      points: [],
    },
  },
  jobs: [
    {
      period: "Aug 2026 — present",
      role: "Senior Software Engineer",
      org: "S4E",
      points: [
        "I lead the team modernizing a legacy ERP, from AS-IS/TO-BE mapping to production delivery.",
        "I write ADRs, diagrams and API contracts that reduce reliance on tacit knowledge.",
        "I set standards through code review, mentoring and alignment across squads.",
      ],
    },
    {
      period: "Jan 2025 — Aug 2026",
      role: "Full Stack Developer",
      org: "UniChristus",
      points: [
        "Designed Java (Spring Boot) and Go microservices with independent deploys.",
        "Integrated OCR, ICR and Text-to-Speech to generate, read and grade assessments.",
        "Led architecture and code review with Docker, CI/CD and GCP.",
      ],
    },
    {
      period: "Mar 2023 — Dec 2024",
      role: "Full Stack Intern",
      org: "UniChristus",
      points: ["Shipped features in Angular, React and Vue in two-week cycles.", "Optimized Spring Boot APIs and high-volume PostgreSQL queries."],
    },
  ],
  education: [
    { period: "2026 — 2027", title: "M.Sc. in Applied Informatics", org: "UNIFOR · in progress" },
    { period: "2022 — 2025", title: "B.Sc. in Computer Science", org: "UNIFOR" },
  ],
  career: [
    { year: "2026", type: "feat", scope: "s4e", msg: "take on the legacy ERP modernization as Senior Software Engineer", job: 0 },
    { year: "2026", type: "feat", scope: "masters", msg: "start M.Sc. in Applied Informatics (UNIFOR · in progress)" },
    { year: "2025", type: "release", scope: "degree", msg: "complete B.Sc. in Computer Science at UNIFOR" },
    { year: "2025", type: "feat", scope: "unichristus", msg: "promoted to Full Stack Developer", job: 1 },
    { year: "2023", type: "feat", scope: "unichristus", msg: "start as full stack intern", job: 2 },
    { year: "2022", type: "chore", scope: "degree", msg: "init: Computer Science at UNIFOR" },
  ],
  toolbox: [
    { group: "Languages", items: ["Java", "Go", "Python", "TypeScript", "JavaScript", "C#", "C", "Clojure (for fun)"] },
    { group: "Backend", items: ["Spring Boot", "Gin", "FastAPI", "Node.js / Express", ".NET", "REST", "gRPC", "RabbitMQ"] },
    { group: "Frontend", items: ["Angular", "React", "Svelte", "Next.js", "Tiptap / ProseMirror", "SCSS", "Web Components"] },
    {
      group: "AI",
      items: ["LLMs", "RAG", "LangChain / LangGraph", "HuggingFace", "BERTimbau", "Gemini and Anthropic APIs", "YOLO · SAM2 · OpenCV", "OCR · ICR · TTS", "PyTorch · TensorFlow"],
    },
    { group: "Data & Infra", items: ["PostgreSQL · pgvector", "MongoDB", "Docker", "Kubernetes", "GCP", "CI/CD", "GitFlow"] },
    { group: "Process", items: ["Microservices", "DDD", "SOLID", "TDD", "AS-IS / TO-BE", "ADR", "Scrum"] },
  ],
  principles: [
    {
      title: "A decision without a record is a lost decision",
      text: "In legacy systems, the rules live in a few people's heads. Every relevant decision becomes a short ADR, versioned with the code.",
    },
    {
      title: "AS-IS before TO-BE",
      text: "Rewriting without understanding the current flow reproduces the same problems with new technology. I document what exists first.",
    },
    { title: "Boundaries before frameworks", text: "I separate HTTP, business rules and integrations. Switching providers becomes configuration, not refactoring." },
    {
      title: "AI where it removes work",
      text: "I apply models to manual, repetitive steps, like reading and grading exams. The gain shows up as an eliminated step.",
    },
    { title: "If it bothers me twice, it becomes a tool", text: "Small, recurring friction is expensive. That's why I write small CLIs for the team." },
    { title: "Code review is asynchronous mentoring", text: "I explain the why, point to the pattern and leave a link to the guide." },
  ],
  labels: ["full-stack", "applied-ai", "legacy", "research"],
  checklist: [
    "3+ years in production, from intern to senior engineer",
    "Microservice architecture in Java and Go",
    "AI applied to real steps (OCR, ICR, TTS, LLMs, computer vision)",
    "Two published papers and an M.Sc. in progress",
  ],
  ui: enUi,
};
