import type { Copy } from ".";

export const ptUi = {
  locale: "pt-BR",
  org: "sua-empresa",
  repo: "time-de-engenharia",
  shortcuts: "Atalhos",
  cv: "Currículo PDF",
  title: (role: string) => `Contratar Thiago Sampaio como ${role}`,
  open: "Aberto",
  mergeInto: (n: number) => `quer fazer merge de ${n} commits em`,
  fromBranch: "a partir de",
  tablist: "Seções do pull request",
  tabs: { conversation: "Conversa", commits: "Commits", checks: "Checks", files: "Arquivos alterados" },
  diffstat: (n: number) => `${n} linhas adicionadas, 0 removidas`,
  footer: "Escrito como um pull request. Nenhum GitHub foi ferido.",

  prefs: "Preferências",
  palette: "Tema de cores",
  palettes: { lime: "Lima", ocean: "Oceano", rose: "Rosa", amber: "Âmbar", light: "Claro" },
  language: "Idioma",

  described: "descreveu este pull request",
  author: "Autor",
  hSummary: "Resumo",
  hNow: "O que entra com este merge",
  hTest: "Como testar",
  hChecklist: "Checklist",
  addedLabels: "adicionou os rótulos",
  addedCommits: (n: number) => `adicionou ${n} commits`,
  seeCommits: (n: number) => `ver os ${n} commits →`,
  selfReviewed: "revisou as próprias mudanças",
  selfReview: "Auto-revisão",
  principlesIntro: "Princípios que guiam meu trabalho, anotados em PRINCIPIOS.md:",

  allPassed: "Todas as checagens passaram",
  checksLine: (n: number) => `${n} checagens de stack, princípios e GitHub`,
  ghDown: "GitHub sem resposta agora",
  ghLoading: "consultando o GitHub…",
  ghLine: (repos: number, stars: number, last: string) => `${repos} repositórios, ${stars} estrelas, último push ${last}`,
  details: "detalhes",
  noConflicts: "Sem conflitos com a base",
  noConflictsText: "Base em Fortaleza – CE. Este branch pode entrar na sua base sem retrabalho.",
  merge: "Merge pull request",
  confirmQ: "Confirmar merge?",
  confirmNext: "O próximo passo é uma conversa.",
  confirm: "Confirmar merge",
  mailSubject: "Sobre o PR #5232",
  copyEmail: "copiar e-mail",
  copied: "e-mail copiado ✓",
  cancel: "cancelar",

  sidebar: "Detalhes do pull request",
  reviewers: "Revisores",
  reviewPending: "Você · revisão pendente",
  assignee: "Responsável",
  labelsH: "Rótulos",
  milestone: "Marco",
  milestoneText: "S4E · modernização de ERP legado",
  attachments: "Anexos",

  commitsOf: (y: string) => `Commits de ${y}`,
  openScope: (s: string) => `Abrir ${s}`,

  checksPassed: (n: number) => `${n} checagens passaram`,
  oneRunning: ", 1 em andamento",
  oneNeutral: ", 1 neutra",
  verifications: (n: number) => `${n} verificações · ok`,
  lintName: "lint / princípios",
  lintRules: (n: number) => `${n} regras · 0 avisos`,
  ghName: "github / atividade pública",
  live: "ao vivo · api.github.com",
  passed: "passou",
  running: "em andamento",
  neutral: "neutra",
  ghFailed: "O GitHub não respondeu agora. Tente mais tarde ou abra o perfil.",
  loading: "consultando…",
  repos: "repositórios públicos",
  stars: "estrelas",
  lastPush: "último push",
  langs: "linguagens recentes",

  files: "Arquivos",
  binary: "arquivo binário",
  screenshot: (t: string) => `Captura de tela: ${t}`,
  diff: { status: "status", year: "ano", role: "papel", result: "resultado" },
};

export const pt: Copy = {
  meta: {
    title: "Thiago Sampaio · Engenheiro de Software Sênior",
    description: "Thiago de Oliveira Sampaio, Engenheiro de Software Sênior em Fortaleza. Full stack, IA aplicada e modernização de sistemas legados.",
  },
  role: "Engenheiro de Software Sênior",
  bio: [
    "Construo software que precisa durar: plataformas educacionais que atendem várias instituições, ERPs legados que viram arquitetura moderna sem parar a operação e, nas horas vagas, modelos de IA que reconhecem Pokémon desenhados à mão.",
    "Hoje lidero a modernização de um ERP legado na S4E. Antes, passei mais de três anos na UniChristus, de estagiário a desenvolvedor full stack, projetando microsserviços em Java e Go e colocando OCR, ICR e TTS para corrigir provas. Sou bacharel em Ciência da Computação e mestrando em Informática Aplicada na UNIFOR.",
  ],
  now: [
    {
      title: "Modernizando um ERP legado",
      text: "Na S4E desde agosto de 2026: mapeio o AS-IS, desenho o TO-BE e transformo conhecimento tácito em ADRs, contratos de API e guias.",
    },
    {
      title: "Cidades, bacias e lixo urbano",
      text: "Clusterizo cidades com o City Clustering Algorithm e cruzo com o potencial de deságue das bacias para prever o plástico que chega aos rios.",
    },
    {
      title: "LLMs sem amarra de provedor",
      text: "O Professor Carvalho troca de Ollama local para qualquer API OpenAI-compatible mudando 3 variáveis de ambiente.",
    },
  ],
  status: { production: "em produção", oss: "open source", research: "pesquisa", lab: "experimento" },
  linkLabel: { repo: "código", demo: "demo ao vivo", doc: "documento" },
  projects: {
    exitus: {
      title: "Ecossistema Educacional Exitus",
      role: "Full Stack · arquitetura",
      metric: { value: "12", label: "módulos integrados" },
      summary:
        "Plataforma educacional multi-tenant que atende várias instituições numa única base: avaliações, editor de conteúdo, correção automática, comunicação e mais.",
      points: [
        "Microsserviços em Java (Spring Boot) e Go com deploys independentes por domínio.",
        "Pipelines de OCR, ICR e TTS que geram, leem e corrigem provas sem etapas manuais.",
        "Modernização de módulos legados integrando sistemas internos e externos por API.",
      ],
    },
    tiptap: {
      title: "Exitus Editor",
      role: "Autor · biblioteca",
      summary:
        "Editor rich-text sobre Tiptap/ProseMirror com fórmulas, imagens e manipulação de conteúdo, usado como editor único em vários módulos.",
      points: [
        "Inicialização mínima: um elemento HTML e um arquivo JS.",
        "Corretor ortográfico integrado, servido por um microsserviço em Go.",
        "Extensões customizadas para conteúdo de avaliações.",
      ],
    },
    profoak: {
      title: "Professor Carvalho",
      role: "Autor",
      metric: { value: "3", label: "env vars para trocar de LLM" },
      summary: "API FastAPI de um assistente com a persona permanente do Professor Carvalho, independente de provedor de LLM.",
      points: [
        "Camadas routes → services → models: o endpoint é testado com um LLM falso via dependency_overrides.",
        "Roda em Ollama local, vLLM ou Groq/Together trocando só LLM_BASE_URL, LLM_API_KEY e LLM_MODEL.",
        "Remove blocos <think> de modelos de raciocínio para não quebrar a persona nem estourar tokens.",
        "Deploy com Docker Compose na Oracle Cloud Free Tier.",
      ],
    },
    pavimento: {
      title: "Patologias em pavimento asfáltico",
      role: "Pesquisador · TCC",
      metric: { value: "93,2%", label: "de precisão" },
      summary: "Visão computacional que detecta e segmenta falhas em vias urbanas a partir de fotos, com dataset próprio anotado à mão.",
      points: [
        "YOLOv11X com transfer learning a partir de pesos COCO.",
        "Segmentação com SAM2 e fine-tuning controlado contra overfitting.",
        "Dataset próprio com 757 imagens anotadas.",
      ],
    },
    pokeguess: {
      title: "PokéGuess",
      role: "Autor",
      metric: { value: "251", label: "Pokémon reconhecidos" },
      summary: "Você desenha um Pokémon e o modelo diz qual é. Classifica esboços das gerações 1 e 2 em tempo real.",
      points: ["Transfer learning com MobileNetV2 e fine-tuning em 2 fases.", "Data augmentation forte para compensar poucos exemplos por classe."],
    },
    ticket: {
      title: "Ticket Maker",
      role: "Autor",
      summary: "RAG sobre a documentação do time: indexa Markdown no pgvector e usa Gemini para montar tickets integrados ao OpenProject.",
      points: ["Ingestão de documentos com reindexação limpa e diretórios configuráveis.", "Migrações versionadas com Alembic sobre PostgreSQL + pgvector."],
    },
    cca: {
      title: "City Clustering Algorithm",
      role: "Pesquisador · mestrado",
      metric: { value: "10⁶+", label: "sítios processáveis" },
      summary: "CCA para regionalização: agrupa setores ou pixels populacionais em clusters urbanos por densidade e distância haversine.",
      points: [
        "KD-tree sobre a esfera: mesmo resultado do laço par-a-par, rodando em milhões de sítios.",
        "Funciona com pontos (setores censitários) e rasters (GPW).",
      ],
    },
    intent: {
      title: "Intenção de mensagens de estudantes",
      role: "Pesquisador",
      summary: "Pipeline de PLN que classifica mensagens de alunos por intenção e decide qual fluxo de IA responde.",
      points: [
        "Fine-tuning de BERTimbau com HuggingFace.",
        "Orquestração com Gemini conforme a categoria detectada.",
        "Publicado no XXVI Encontro de Pós-Graduação e Pesquisa da UNIFOR.",
      ],
    },
    medsystem: {
      title: "Med System",
      role: "Full Stack",
      summary: "Apoio a médicos externos e estudantes da UniChristus: atendimento clínico, apoio ao diagnóstico, receitas e rotinas médicas.",
      points: ["Mensageria com RabbitMQ entre serviços Node.js.", "Interface React + Tailwind para uso durante o atendimento."],
    },
    optasks: {
      title: "op-tasks-cli",
      role: "Autor",
      summary: "CLI via npx que sincroniza tarefas do OpenProject com arquivos Markdown locais, nos dois sentidos.",
      points: ["Token salvo no diretório home, nunca no repositório.", "Seleção interativa de projetos; baixa só tarefas abertas atribuídas a você."],
    },
    bancosync: {
      title: "banco-sync-cli",
      role: "Autor",
      summary:
        "Mantém os arquivos SQL de migração em sincronia com o PostgreSQL real, usando Gemini para reescrevê-los e mostrando um diff antes de salvar.",
      points: ["Saída JSON estruturada do Gemini 2.5 Flash para preservar comentários e estilo."],
    },
    katex: {
      title: "appKatex",
      role: "Autor",
      summary: "Diretiva Angular standalone e reativa (Signals) que renderiza LaTeX com KaTeX em qualquer componente.",
      points: ["Detecta $$…$$, \\[…\\] e \\(…\\) automaticamente.", "Escapa HTML que não é LaTeX para evitar XSS."],
    },
    spell: {
      title: "Spell checker em Go",
      role: "Autor",
      summary: "Microsserviço containerizado em Go que fornece correção ortográfica ao Exitus Editor.",
      points: ["Serviço isolado, com deploy independente do editor."],
    },
    pokeia: {
      title: "PokeIA",
      role: "Autor",
      summary: 'Pokédex semântica: busque "pokémon de fogo que voa" e receba Charizard. Também recomenda times.',
      points: ["Busca vetorial com Sentence-Transformers + FAISS."],
    },
    sqlguard: {
      title: "SQL Guard",
      role: "Autor",
      summary: "Laboratório que mostra fluxos de autenticação seguros e vulneráveis a SQL injection lado a lado.",
      points: ["Supabase Functions no backend, shadcn/ui + Radix no frontend."],
    },
    agendamento: {
      title: "Agendamento de consultas",
      role: "Autor",
      summary: "Marcação de consultas com psicólogos, com Google Sheets como painel da clínica e sincronização via Apps Script.",
      points: ["Angular no front, Express + MongoDB no back."],
    },
    readme: {
      title: "Gerador de README com IA",
      role: "Autor",
      summary: "GPT-2 fine-tunado em READMEs do GitHub para gerar documentação, com API e interface no HuggingFace Spaces.",
      points: ["Pipeline completo: coleta, pré-processamento, treino e avaliação."],
    },
    topatudo: {
      title: "TopaTudo",
      role: "Autor",
      summary: "Marketplace para contratar prestadores de serviço, com jornadas de cliente e prestador. Meu repo mais estrelado.",
      points: ["Contas de teste: teste@teste.com ou prestador@teste.com, senha 12."],
    },
    termo: {
      title: "Termo Musical",
      role: "Autor",
      summary: "Um Termo para adivinhar o artista ouvindo 2 segundos de música. Desafio diário e modo prática.",
      points: ["Next.js 14 com App Router e Web Audio API."],
    },
    blockchain: {
      title: "Blockchain em Clojure",
      role: "Autor",
      summary: "Uma blockchain escrita inteiramente em Clojure, para entender imutabilidade e encadeamento de hashes.",
      points: [],
    },
  },
  jobs: [
    {
      period: "ago/2026 — atual",
      role: "Engenheiro de Software Sênior",
      org: "S4E",
      points: [
        "Lidero o time que moderniza um ERP legado, do levantamento AS-IS/TO-BE à entrega em produção.",
        "Produzo ADRs, diagramas e contratos de API que reduzem a dependência de conhecimento tácito.",
        "Defino padrões por code review, mentoria e alinhamento entre squads.",
      ],
    },
    {
      period: "jan/2025 — ago/2026",
      role: "Desenvolvedor Full Stack",
      org: "UniChristus",
      points: [
        "Projetei microsserviços em Java (Spring Boot) e Go com deploys independentes.",
        "Integrei OCR, ICR e Text-to-Speech para gerar, ler e corrigir avaliações.",
        "Liderei arquitetura e code review com Docker, CI/CD e GCP.",
      ],
    },
    {
      period: "mar/2023 — dez/2024",
      role: "Estagiário Full Stack",
      org: "UniChristus",
      points: ["Entreguei features em Angular, React e Vue em ciclos quinzenais.", "Otimizei APIs Spring Boot e consultas PostgreSQL de alto volume."],
    },
  ],
  education: [
    { period: "2026 — 2027", title: "Mestrado em Informática Aplicada", org: "UNIFOR · em andamento" },
    { period: "2022 — 2025", title: "Bacharelado em Ciência da Computação", org: "UNIFOR" },
  ],
  career: [
    { year: "2026", type: "feat", scope: "s4e", msg: "assume a modernização do ERP legado como Engenheiro de Software Sênior", job: 0 },
    { year: "2026", type: "feat", scope: "mestrado", msg: "inicia Mestrado em Informática Aplicada (UNIFOR · em andamento)" },
    { year: "2025", type: "release", scope: "formacao", msg: "conclui Bacharelado em Ciência da Computação na UNIFOR" },
    { year: "2025", type: "feat", scope: "unichristus", msg: "promovido a Desenvolvedor Full Stack", job: 1 },
    { year: "2023", type: "feat", scope: "unichristus", msg: "começa como estagiário full stack", job: 2 },
    { year: "2022", type: "chore", scope: "formacao", msg: "init: Ciência da Computação na UNIFOR" },
  ],
  toolbox: [
    { group: "Linguagens", items: ["Java", "Go", "Python", "TypeScript", "JavaScript", "C#", "C", "Clojure (por diversão)"] },
    { group: "Backend", items: ["Spring Boot", "Gin", "FastAPI", "Node.js / Express", ".NET", "REST", "gRPC", "RabbitMQ"] },
    { group: "Frontend", items: ["Angular", "React", "Svelte", "Next.js", "Tiptap / ProseMirror", "SCSS", "Web Components"] },
    {
      group: "IA",
      items: ["LLMs", "RAG", "LangChain / LangGraph", "HuggingFace", "BERTimbau", "Gemini e Anthropic API", "YOLO · SAM2 · OpenCV", "OCR · ICR · TTS", "PyTorch · TensorFlow"],
    },
    { group: "Dados & Infra", items: ["PostgreSQL · pgvector", "MongoDB", "Docker", "Kubernetes", "GCP", "CI/CD", "GitFlow"] },
    { group: "Processo", items: ["Microsserviços", "DDD", "SOLID", "TDD", "AS-IS / TO-BE", "ADR", "Scrum"] },
  ],
  principles: [
    {
      title: "Decisão sem registro é decisão perdida",
      text: "Em legado, as regras moram na cabeça de poucas pessoas. Toda decisão relevante vira um ADR curto, versionado com o código.",
    },
    {
      title: "AS-IS antes do TO-BE",
      text: "Reescrever sem entender o fluxo atual reproduz os mesmos problemas com tecnologia nova. Primeiro documento o que existe.",
    },
    { title: "Fronteiras antes de frameworks", text: "Separo HTTP, regra de negócio e integrações. Trocar de provedor vira configuração, não refatoração." },
    {
      title: "IA onde remove trabalho",
      text: "Aplico modelos em etapas manuais e repetitivas, como ler e corrigir provas. O ganho aparece como etapa eliminada.",
    },
    { title: "Incomodou duas vezes, vira ferramenta", text: "Atrito pequeno e recorrente custa caro. Por isso escrevo CLIs pequenas para o time." },
    { title: "Code review é mentoria assíncrona", text: "Comento o porquê, aponto o padrão e deixo o link para o guia." },
  ],
  labels: ["full-stack", "ia-aplicada", "legado", "pesquisa"],
  checklist: [
    "3+ anos em produção, de estagiário a engenheiro sênior",
    "Arquitetura de microsserviços em Java e Go",
    "IA aplicada em etapas reais (OCR, ICR, TTS, LLMs, visão computacional)",
    "Duas publicações e mestrado em andamento",
  ],
  ui: ptUi,
};
